<a href="https://colab.research.google.com/github/aemiralfath/BPML-Dicoding/blob/master/nlp_2_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
! pip install --upgrade --force-reinstall --no-deps kaggle
! mkdir /root/.kaggle/
! cp "/content/drive/My Drive/Machine Learning/kaggle.json" /root/.kaggle/
! chmod 600 /root/.kaggle/kaggle.json

     |████████████████████████████████| 61kB 2.9MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.6-cp36-none-any.whl size=72859 sha256=7b12356be4306621df0a4a5045c5a56b90984bca0f5fce6d814b2abad4060d6e
  Stored in directory: /root/.cache/pip/wheels/57/4e/e8/bb28d035162fb8f17f8ca5d42c3230e284c6aa565b42b72674
Successfully built kaggle
  Found existing installation: kaggle 1.5.6
    Uninstalling kaggle-1.5.6:
      Successfully uninstalled kaggle-1.5.6


In [3]:
!kaggle datasets download -d marklvl/sentiment-labelled-sentences-data-set

  0% 0.00/326k [00:00<?, ?B/s]
100% 326k/326k [00:00<00:00, 77.4MB/s]


In [4]:
import zipfile

zipref = zipfile.ZipFile('sentiment-labelled-sentences-data-set.zip', 'r')
zipref.extractall()
zipref.close()

In [34]:
import pandas as pd

df = pd.read_csv('sentiment labelled sentences/yelp_labelled.txt', names=['sentence', 'label'], sep='\t')

In [35]:
df.tail()

sentence  label
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

In [36]:
from sklearn.model_selection import train_test_split

sentences = df['sentence'].values
y = df['label'].values

x_train, x_test, y_train, y_test = train_test_split(sentences, y, test_size=0.2)

In [37]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=1000, oov_token='<OOV>')
tokenizer.fit_on_texts(x_train)

sequence_train = tokenizer.texts_to_sequences(x_train)
sequence_test = tokenizer.texts_to_sequences(x_test)
sequence_val = tokenizer.texts_to_sequences(x_val)

padded_train = pad_sequences(sequence_train, padding='post', maxlen=30, truncating='post')
padded_test = pad_sequences(sequence_test, padding='post', maxlen=30, truncating='post')
padded_val = pad_sequences(sequence_val, padding='post', maxlen=30, truncating='post')

In [38]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'was': 4,
 'i': 5,
 'a': 6,
 'to': 7,
 'is': 8,
 'this': 9,
 'it': 10,
 'of': 11,
 'food': 12,
 'not': 13,
 'in': 14,
 'for': 15,
 'place': 16,
 'good': 17,
 'we': 18,
 'service': 19,
 'had': 20,
 'my': 21,
 'with': 22,
 'so': 23,
 'that': 24,
 'be': 25,
 'very': 26,
 'have': 27,
 'were': 28,
 'are': 29,
 'back': 30,
 'great': 31,
 'you': 32,
 'they': 33,
 'at': 34,
 'but': 35,
 'here': 36,
 'on': 37,
 'all': 38,
 'time': 39,
 'our': 40,
 'go': 41,
 'really': 42,
 'like': 43,
 'will': 44,
 'there': 45,
 'best': 46,
 'just': 47,
 'an': 48,
 'their': 49,
 'as': 50,
 'restaurant': 51,
 "don't": 52,
 'up': 53,
 'nice': 54,
 'would': 55,
 'if': 56,
 'ever': 57,
 'one': 58,
 'your': 59,
 'only': 60,
 'from': 61,
 'never': 62,
 'which': 63,
 'friendly': 64,
 'also': 65,
 'vegas': 66,
 'been': 67,
 "i've": 68,
 'did': 69,
 'no': 70,
 'amazing': 71,
 'definitely': 72,
 'delicious': 73,
 "i'm": 74,
 'us': 75,
 "won't": 76,
 'get': 77,
 'or': 78,
 'by': 79,
 'o

In [39]:
print(padded_train)
print(padded_test)
print(padded_val)

[[  2 497 190 ...   0   0   0]
 [499 370  65 ...   0   0   0]
 [371   3  13 ...   0   0   0]
 ...
 [393 528   1 ...   0   0   0]
 [  9  16 770 ...   0   0   0]
 [ 79   9 726 ...   0   0   0]]
[[  2 508   8 ...   0   0   0]
 [182  58   1 ...   0   0   0]
 [  1   7 113 ...   0   0   0]
 ...
 [  5   1 259 ...   0   0   0]
 [ 13  17  15 ...   0   0   0]
 [  2 403 503 ...   0   0   0]]
[[ 51   8 128 ...   0   0   0]
 [  2  60   1 ...   0   0   0]
 [281   7   1 ... 340   0   0]
 ...
 [ 25 249   7 ...   0   0   0]
 [  2  19   4 ...   0   0   0]
 [105 134 121 ...   0   0   0]]


In [40]:
print(len(padded_train[0]))
print(len(padded_test[0]))
print(len(padded_val[0]))

30
30
30


In [45]:
import tensorflow as tf

model = tf.keras.Sequential([
                             tf.keras.layers.Embedding(1000, 32, input_length=30),
                             tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
                            #  tf.keras.layers.GlobalAveragePooling1D(),
                             tf.keras.layers.Dropout(0.5),
                             tf.keras.layers.Flatten(),
                             tf.keras.layers.Dense(24, activation='relu'),
                             tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 30, 32)            32000     
_________________________________________________________________
bidirectional_6 (Bidirection (None, 128)               49664     
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
flatten_5 (Flatten)          (None, 128)               0         
_________________________________________________________________
dense_14 (Dense)             (None, 24)                3096      
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 25        
Total params: 84,785
Trainable params: 84,785
Non-trainable params: 0
__________________________________________________

In [46]:
num_epochs = 20
history = model.fit(
    padded_train,
    y_train,
    epochs=num_epochs,
    validation_data=(padded_val, y_val)
)

Epoch 1/20
25/25 [==============================] - 1s 34ms/step - loss: 0.6928 - accuracy: 0.5025 - val_loss: 0.6893 - val_accuracy: 0.6900
Epoch 2/20
25/25 [==============================] - 0s 8ms/step - loss: 0.6857 - accuracy: 0.5663 - val_loss: 0.6689 - val_accuracy: 0.7400
Epoch 3/20
25/25 [==============================] - 0s 8ms/step - loss: 0.6074 - accuracy: 0.7350 - val_loss: 0.4804 - val_accuracy: 0.8050
Epoch 4/20
25/25 [==============================] - 0s 8ms/step - loss: 0.3944 - accuracy: 0.8487 - val_loss: 0.3575 - val_accuracy: 0.8450
Epoch 5/20
25/25 [==============================] - 0s 8ms/step - loss: 0.2295 - accuracy: 0.9125 - val_loss: 0.2574 - val_accuracy: 0.9200
Epoch 6/20
25/25 [==============================] - 0s 8ms/step - loss: 0.1524 - accuracy: 0.9538 - val_loss: 0.2163 - val_accuracy: 0.9300
Epoch 7/20
25/25 [==============================] - 0s 8ms/step - loss: 0.1102 - accuracy: 0.9575 - val_loss: 0.2279 - val_accuracy: 0.9400
Epoch 8/20
25/25 [=